version: 2
updates:
  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ['dependencies', 'dashboard']
    groups:
      all-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: /bot
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ['dependencies', 'bot']
    groups:
      all-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: /ingest
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ['dependencies', 'ingest']
    groups:
      all-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ['dependencies', 'web']
    groups:
      all-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ['ci']
    groups:
      actions:
        patterns: ["*"]
