-- Schemat Supabase dla dashboardu Bot DC.
-- Wklej w Supabase → SQL Editor, lub seeder uruchomi to przez service_role.

create table if not exists public.games (
  id              bigint generated by default as identity primary key,
  platform        text not null,
  platform_app_id text not null,
  title           text not null,
  igdb_id         bigint,
  release_year    int,
  genres          text,           -- JSON: string[]
  summary         text,
  cover_url       text,
  playtime_min    int default 0,
  last_played     bigint,
  updated_at      bigint,
  unique (platform, platform_app_id)
);
create index if not exists idx_games_platform on public.games (platform);
create index if not exists idx_games_playtime on public.games (playtime_min desc);

create table if not exists public.settings (
  key   text primary key,
  value text
);

-- Dostęp serwerowy przez service_role (omija RLS). Jeśli wystawiasz anon do klienta,
-- włącz RLS i dodaj polityki tylko-do-odczytu na games.
alter table public.games enable row level security;
alter table public.settings enable row level security;

drop policy if exists "games read" on public.games;
create policy "games read" on public.games for select using (true);
